import type { INodeProperties } from 'n8n-workflow';
import { accountIdField } from '../shared/AccountIdField';
import { returnAllFields } from '../shared/pagination';

export const calendarListEventsFields: INodeProperties[] = [
	{
		displayName: 'Calendar ID',
		name: 'calendarId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['calendar'],
				operation: ['calendarListEvents'],
			},
		},
	},
	accountIdField({ resource: 'calendar', operation: 'calendarListEvents' }),
	...returnAllFields({ resource: 'calendar', operation: 'calendarListEvents' }),
	{
		displayName: 'Additional Filters',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		options: [
			{
				displayName: 'Attendees',
				name: 'attendees',
				type: 'string',
				default: '',
				description: 'Comma-separated list of attendee emails',
				routing: { send: { type: 'query', property: 'attendees' } },
			},
			{
				displayName: 'Busy',
				name: 'busy',
				type: 'boolean',
				default: false,
				description: 'Whether to filter for events with status busy',
				routing: { send: { type: 'query', property: 'busy' } },
			},
			{
				displayName: 'Cancelled',
				name: 'isCancelled',
				type: 'boolean',
				default: false,
				description: 'Whether to retrieve cancelled events',
				routing: { send: { type: 'query', property: 'is_cancelled' } },
			},
			{
				displayName: 'Cursor',
				name: 'cursor',
				type: 'string',
				default: '',
				description: 'Ignored when Return All is enabled',
				routing: { send: { type: 'query', property: 'cursor' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'Filter by description',
				routing: { send: { type: 'query', property: 'description' } },
			},
			{
				displayName: 'End',
				name: 'end',
				type: 'string',
				default: '',
				description: 'Filter events ending before this date',
				routing: { send: { type: 'query', property: 'end' } },
			},
			{
				displayName: 'Event Type',
				name: 'eventType',
				type: 'string',
				default: '',
				description: 'Comma-separated list of event types',
				routing: { send: { type: 'query', property: 'event_type' } },
			},
			{
				displayName: 'Expand Recurring',
				name: 'expandRecurring',
				type: 'boolean',
				default: false,
				description: 'Whether to expand recurring events (single or occurrence)',
				routing: { send: { type: 'query', property: 'expand_recurring' } },
			},
			{
				displayName: 'iCal UID',
				name: 'icalUid',
				type: 'string',
				default: '',
				description: 'Filter by iCal UID',
				routing: { send: { type: 'query', property: 'ical_uid' } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				description: 'Filter by location',
				routing: { send: { type: 'query', property: 'location' } },
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				description: 'Pagination offset',
				typeOptions: { minValue: 0 },
				routing: { send: { type: 'query', property: 'offset' } },
			},
			{
				displayName: 'Start',
				name: 'start',
				type: 'string',
				default: '',
				description: 'Filter events starting after this date',
				routing: { send: { type: 'query', property: 'start' } },
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: 'Filter by title',
				routing: { send: { type: 'query', property: 'title' } },
			},
			{
				displayName: 'Updated After',
				name: 'updatedAfter',
				type: 'string',
				default: '',
				description: 'Filter events updated after this date',
				routing: { send: { type: 'query', property: 'updated_after' } },
			},
			{
				displayName: 'Updated Before',
				name: 'updatedBefore',
				type: 'string',
				default: '',
				description: 'Filter events updated before this date',
				routing: { send: { type: 'query', property: 'updated_before' } },
			},
		],
		displayOptions: {
			show: {
				resource: ['calendar'],
				operation: ['calendarListEvents'],
			},
		},
	},
];
